name: progetto_flutter
description: Un semplice progetto Flutter
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.2
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true