name: progetto_flutter
description: Un semplice progetto Flutter
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0
  flutter_lints: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
test_api: ^0.7.7
flutter:
  uses-material-design: true